name: "✨ Feature Request"
description: "Suggest a new feature or improvement"
title: "[FEATURE] <title>"
labels: ["enhancement", "discussion"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Describe the feature you’d like to see."
      placeholder: "A short summary of the feature request."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve?"
      placeholder: "Explain the use case or challenge this feature will address."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Describe how this feature should work."
      placeholder: "Detail how the feature should behave and any key implementation details."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered other solutions or workarounds?"
      placeholder: "If there are existing workarounds, list them."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked for similar feature requests"
          required: true
        - label: "I have provided all necessary details"
          required: true
