name: "🐛 Bug Report"
description: "Report an issue or unexpected behavior"
title: "[BUG] <title>"
labels: ["bug", "triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A concise description of the issue."
      placeholder: "Describe the bug in one or two sentences."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide a step-by-step guide to reproduce the issue."
      placeholder: |
        1. Navigate to...
        2. Click on...
        3. Observe the issue...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what should have happened."
      placeholder: "The expected result is..."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened."
      placeholder: "The observed result is..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Provide system details (OS, browser, version, etc.)."
      placeholder: |
        - OS: Windows/Mac/Linux
        - Browser: Chrome/Firefox/Safari
        - Version: x.x.x
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have searched for similar issues"
          required: true
        - label: "I have provided sufficient information"
          required: true
